server:
  port: 8080
spring:
  application:
    name: spring-boot
  datasource:
    password: vullnet2004
    url: jdbc:postgresql://localhost:5432/micro
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
